version: 1.1
cameras
  - name: CameraFrontRGB
    enabled: false
    model: ARRIVAL Generic Camera
    pose: 
      x: 2.099975
      y: -0.000102
      z: 0.7
      pitch: 0.0
      roll: 0.0
      yaw: 0.0
    transport: 
      zmq: tcp://0.0.0.0:8008
  - name: CameraFrontSegm
    enabled: false
    model: ARRIVAL Generic Camera
    pose: 
      x: 2.099975
      y: -0.000102
      z: 0.7
      pitch: 0.0
      roll: 0.0
      yaw: 0.0
    transport: 
      zmq: tcp://0.0.0.0:9008
  - name: CameraBirdsEye
    enabled: false
    model: ARRIVAL Generic Camera
    pose: 
      x: 0.000066
      y: 0.000041
      z: 30.000044
      pitch: 59.999207
      roll: 0.00001
      yaw: 0.000246
    transport: 
      zmq: tcp://0.0.0.0:10008
  - name: CameraBirdsEyeSegm
    enabled: false
    model: ARRIVAL Generic Camera
    pose: 
      x: 0.000042
      y: -0.000064
      z: 30.000025
      pitch: 59.999447
      roll: 0.000015
      yaw: 0.000064
    transport: 
      zmq: tcp://0.0.0.0:10009
  - name: CameraLeftRGB
    enabled: false
    model: ARRIVAL Generic Camera
    pose: 
      x: 1.279986
      y: 0.380003
      z: 0.550007
      pitch: 20.000002
      roll: 0.0
      yaw: 50.000092
    transport: 
      zmq: tcp://0.0.0.0:8009
  - name: CameraRightRGB
    enabled: false
    model: ARRIVAL Generic Camera
    pose: 
      x: 1.280036
      y: -0.380033
      z: 0.550005
      pitch: 20.000002
      roll: 0.000009
      yaw: -50.000145
    transport: 
      zmq: tcp://0.0.0.0:8010
  - name: CameraLeftSegm
    enabled: false
    model: ARRIVAL Generic Camera
    pose: 
      x: 1.279984
      y: 0.379998
      z: 0.550001
      pitch: 19.999994
      roll: -0.000002
      yaw: 50.000137
    transport: 
      zmq: tcp://0.0.0.0:9009
  - name: CameraRightSegm
    enabled: false
    model: ARRIVAL Generic Camera
    pose: 
      x: 1.280035
      y: -0.38001
      z: 0.55
      pitch: 19.99996
      roll: 0.000005
      yaw: -50.000076
    transport: 
      zmq: tcp://0.0.0.0:9010
lidars
ins
  - name: ImuOxtsSensor
    enabled: false
    model: OxTS RT3000
    pose: 
      x: 1.249956
      y: 0.000055
      z: 0.0
      pitch: 0.0
      roll: 0.0
      yaw: 0.0
    transport: 
      udp: 127.0.0.1:8000
radars
ultrasonics
vehicles
